name: PowerShell script
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  projectsJson:
    description: projectsJson
    required: true
  settingsJson:
    description: settingsJson
    required: true
  workspace:
    description: workspace
    required: true
  type:
    description:  type
    required: true
  refName:
    description: refName
    required: true
runs:
  using: composite
  steps:
    - name: Determine Changed Files
      id: calculateArtifactNames
      shell: ${{ inputs.shell }}
      env:
        _projectsJson: ${{ inputs.projectsJson }}
        settingsJson: ${{ inputs.settingsJson }}
        _workspace: ${{ inputs.workspace }}
        _type: ${{ inputs.type }}
        _refName: ${{ inputs.refName }}
      run: ${{ github.action_path }}/DetermineDeliveryTargets.ps1 -projectsJson $ENV:_projectsJson -settingsJson $ENV:_settings -workspace $ENV:_workspace -type $ENV:_type -refName $ENV:_refName
branding:
  icon: terminal
  color: blue
