name: PowerShell script
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  settingsJson:
    description: Settings from repository in compressed Json format
    required: true
  project:
    description: project
    required: true
  buildMode:
    description:  buildMode
    required: true
  refName:
    description: refName
    required: true
runs:
  using: composite
  steps:
    - name: Determine Changed Files
      id: calculateArtifactNames
      shell: ${{ inputs.shell }}
      env:
        _settingsJson: ${{ inputs.settingsJson }}
      run: ${{ github.action_path }}/CalculateArtifactNames.ps1 -SettingsJson $ENV:_settingsJson -Project ${{ inputs.project }} -BuildMode ${{ inputs.buildMode }} -RefName ${{ inputs.refName }}
branding:
  icon: terminal
  color: blue
